[default]
extend-ignore-identifiers-re = [
    "travle",
]

[files]
extend-exclude = [
    "themes/StarsepTheme",
    "content/kajaki-modlin.md",
    "*.pl.md",
    "assets/boardgamegeek.csv",
    "content/posts/cli.md",
]
